//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.33440
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSMD.Properties {
	
	
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("ICSharpCode.SettingsEditor.SettingsCodeGeneratorTool", "5.0.0.4755")]
	internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
		
		private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
		
		public static Settings Default {
			get {
				return defaultInstance;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("True")]
		public bool Autocompletion {
			get {
				return ((bool)(this["Autocompletion"]));
			}
			set {
				this["Autocompletion"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("True")]
		public bool DeleteOnExit {
			get {
				return ((bool)(this["DeleteOnExit"]));
			}
			set {
				this["DeleteOnExit"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("")]
		public string ExecutablePath {
			get {
				return ((string)(this["ExecutablePath"]));
			}
			set {
				this["ExecutablePath"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("True")]
		public bool ImportsOnTheFly {
			get {
				return ((bool)(this["ImportsOnTheFly"]));
			}
			set {
				this["ImportsOnTheFly"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("v4.0")]
		public string NETVersion {
			get {
				return ((string)(this["NETVersion"]));
			}
			set {
				this["NETVersion"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("False")]
		public bool RandomName {
			get {
				return ((bool)(this["RandomName"]));
			}
			set {
				this["RandomName"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>System.dll</string>
  <string>System.Core.dll</string>
  <string>System.Data.dll</string>
  <string>System.Data.DataSetExtensions.dll</string>
  <string>System.Deployment.dll</string>
  <string>System.Drawing.dll</string>
  <string>System.Windows.Forms.dll</string>
  <string>System.Xml.dll</string>
  <string>System.Xml.Linq.dll</string>
</ArrayOfString>")]
		public global::System.Collections.Specialized.StringCollection ReferencedAssemblies {
			get {
				return ((global::System.Collections.Specialized.StringCollection)(this["ReferencedAssemblies"]));
			}
			set {
				this["ReferencedAssemblies"] = value;
			}
		}
	}
}
